name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: checkout and build openssl and with quic support
        uses: actions/checkout@v3
        with:
          repository: quictls/openssl
          ref: OpenSSL_1_1_1s+quic
          path: openssl
      - run: |
          cd ${{ github.workspace }}/openssl
          ./config enable-tls1_3 --prefix=$PWD/build
          make -j$(nproc)
          make install_sw

      - name: check out and build ngtcp2 with openssl
        uses: actions/checkout@v3
        with:
         repository: ngtcp2/ngtcp2
         path: ngtcp2

      - run: |
          sudo apt-get install libev-dev
          cd ${{ github.workspace }}/ngtcp2
          autoreconf -i
          export PKG_CONFIG_PATH=${{ github.workspace }}/openssl/build/lib/pkgconfig
          mkdir build
          ./configure --prefix=${{ github.workspace }}/ngtcp2/build/ --with-openssl --with-libev
          make -j$(nproc) check
          make install
